In [38]:
import pandas as pd
import os
df = pd.read_csv("../data/raw/cota_2024_laps.csv")

df.head()

,Driver,LapNumber,Compound,TyreLife,Sector1Sec,Sector2Sec,Sector3Sec,LapTimeSec
0,VER,2.0,MEDIUM,2.0,26.845,39.996,33.150,99.991
1,VER,6.0,MEDIUM,6.0,27.069,39.822,32.888,99.779
2,VER,7.0,MEDIUM,7.0,26.838,39.793,33.100,99.731
3,VER,8.0,MEDIUM,8.0,26.809,39.973,33.300,100.082
4,VER,9.0,MEDIUM,9.0,26.901,39.932,33.199,100.032

In [40]:
df = df.dropna()

In [42]:
df.shape

(883, 8)

In [44]:
compound_map = {
    "SOFT": 0,
    "MEDIUM": 1,
    "HARD": 2
}

df["CompoundEncoded"] = df["Compound"].map(compound_map)

In [46]:
df["DriverEncoded"] = df["Driver"].astype("category").cat.codes

In [48]:
race_laps = 56

df["FuelLoadProxy"] = race_laps - df["LapNumber"]

In [50]:
df["TyreDegEffect"] = df["TyreLife"]

In [52]:
df["SectorSum"] = df["Sector1Sec"] + df["Sector2Sec"] + df["Sector3Sec"]

In [54]:
model_df = df[[
    "Driver",
    "DriverEncoded",
    "Compound",
    "CompoundEncoded",
    "TyreLife",
    "FuelLoadProxy",
    "Sector1Sec",
    "Sector2Sec",
    "Sector3Sec",
    "LapTimeSec"
]]

In [56]:
os.makedirs('../data/processed', exist_ok=True)
model_df.to_csv("../data/processed/cota_2024_features.csv", index=False)

In [58]:
model_df.head()

,Driver,DriverEncoded,Compound,CompoundEncoded,TyreLife,FuelLoadProxy,Sector1Sec,Sector2Sec,Sector3Sec,LapTimeSec
0,VER,17,MEDIUM,1,2.0,54.0,26.845,39.996,33.150,99.991
1,VER,17,MEDIUM,1,6.0,50.0,27.069,39.822,32.888,99.779
2,VER,17,MEDIUM,1,7.0,49.0,26.838,39.793,33.100,99.731
3,VER,17,MEDIUM,1,8.0,48.0,26.809,39.973,33.300,100.082
4,VER,17,MEDIUM,1,9.0,47.0,26.901,39.932,33.199,100.032

In [60]:
model_df.shape

(883, 10)